{"priority": "minor", "kind": "enhancement", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/106/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/106.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/106/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/106/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/106/segway-should-output-a-better-error"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/106/vote"}}, "reporter": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "title": "Segway should output a better error message for empty tracks", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Currently if you attempt to use an empty track in Segway you get the following output:\r\n\r\n```shell\r\n/mnt/work1/users/home2/eric.roberts/segway/segway/structure.py:109: RuntimeWarning: invalid value encountered in long_scalars\r\n  / num_datapoints_track, MAX_WEIGHT_SCALE)\r\nParse Error in file 'outputs/DOHH2_bl_umap_10L_10R_traindir/segway.str': expecting integer or floating-point value at or before line 44, near (nan)\r\nExiting Program\r\nTraceback (most recent call last):\r\n  File \"/mnt/work1/users/home2/eric.roberts/.local/bin/segway\", line 11, in <module>\r\n    load_entry_point('segway', 'console_scripts', 'segway')()\r\n  File \"/mnt/work1/users/home2/eric.roberts/segway/segway/run.py\", line 3131, in main\r\n    return runner()\r\n  File \"/mnt/work1/users/home2/eric.roberts/segway/segway/run.py\", line 2923, in __call__\r\n    self.run(*args, **kwargs)\r\n  File \"/mnt/work1/users/home2/eric.roberts/segway/segway/run.py\", line 2884, in run\r\n    self.run_triangulate()\r\n  File \"/mnt/work1/users/home2/eric.roberts/segway/segway/run.py\", line 2188, in run_triangulate\r\n    self.run_triangulate_single(num_segs)\r\n  File \"/mnt/work1/users/home2/eric.roberts/segway/segway/run.py\", line 2184, in run_triangulate_single\r\n    prog(**kwargs)\r\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 81, in __call__\r\n    return self.run(*args, **kwargs)\r\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 212, in run\r\n    self._getoutput(args, kwargs)\r\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 194, in _getoutput\r\n    stdin, stdout, stderr, cwd)\r\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 157, in _popen\r\n    _returncode_error_factory(cmdline, returncode, output, error)\r\n  File \"/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py\", line 57, in _returncode_error_factory\r\n    raise error_cls, (cmdline, returncode, output, error)\r\noptbuild.ReturncodeError: /mnt/work1/users/home2/eric.roberts/arch/Linux-x86_64/opt/gmtk-1.4.3/bin/gmtkTriangulate returned 1\r\n```\r\n\r\nSomehow the RuntimeError does not stop Segway from running and Segway attempt to continue to run until gmtkTraingulate fails since the segway.str is filled with 'nan' entries.\r\n\r\nOn closer inspection this might be a better error caught in genomedata to avoid issues when something like the \"means\" attribute is used on a genomedata archive. Empty tracks will also raise a RuntimeError (division by zero length).", "markup": "markdown", "html": "<p>Currently if you attempt to use an empty track in Segway you get the following output:</p>\n<div class=\"codehilite language-shell\"><pre><span></span>/mnt/work1/users/home2/eric.roberts/segway/segway/structure.py:109: RuntimeWarning: invalid value encountered in long_scalars\n  / num_datapoints_track, MAX_WEIGHT_SCALE<span class=\"o\">)</span>\nParse Error in file <span class=\"s1\">&#39;outputs/DOHH2_bl_umap_10L_10R_traindir/segway.str&#39;</span>: expecting integer or floating-point value at or before line <span class=\"m\">44</span>, near <span class=\"o\">(</span>nan<span class=\"o\">)</span>\nExiting Program\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n  File <span class=\"s2\">&quot;/mnt/work1/users/home2/eric.roberts/.local/bin/segway&quot;</span>, line <span class=\"m\">11</span>, in &lt;module&gt;\n    load_entry_point<span class=\"o\">(</span><span class=\"s1\">&#39;segway&#39;</span>, <span class=\"s1\">&#39;console_scripts&#39;</span>, <span class=\"s1\">&#39;segway&#39;</span><span class=\"o\">)()</span>\n  File <span class=\"s2\">&quot;/mnt/work1/users/home2/eric.roberts/segway/segway/run.py&quot;</span>, line <span class=\"m\">3131</span>, in main\n    <span class=\"k\">return</span> runner<span class=\"o\">()</span>\n  File <span class=\"s2\">&quot;/mnt/work1/users/home2/eric.roberts/segway/segway/run.py&quot;</span>, line <span class=\"m\">2923</span>, in __call__\n    self.run<span class=\"o\">(</span>*args, **kwargs<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/mnt/work1/users/home2/eric.roberts/segway/segway/run.py&quot;</span>, line <span class=\"m\">2884</span>, in run\n    self.run_triangulate<span class=\"o\">()</span>\n  File <span class=\"s2\">&quot;/mnt/work1/users/home2/eric.roberts/segway/segway/run.py&quot;</span>, line <span class=\"m\">2188</span>, in run_triangulate\n    self.run_triangulate_single<span class=\"o\">(</span>num_segs<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/mnt/work1/users/home2/eric.roberts/segway/segway/run.py&quot;</span>, line <span class=\"m\">2184</span>, in run_triangulate_single\n    prog<span class=\"o\">(</span>**kwargs<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span>, line <span class=\"m\">81</span>, in __call__\n    <span class=\"k\">return</span> self.run<span class=\"o\">(</span>*args, **kwargs<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span>, line <span class=\"m\">212</span>, in run\n    self._getoutput<span class=\"o\">(</span>args, kwargs<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span>, line <span class=\"m\">194</span>, in _getoutput\n    stdin, stdout, stderr, cwd<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span>, line <span class=\"m\">157</span>, in _popen\n    _returncode_error_factory<span class=\"o\">(</span>cmdline, returncode, output, error<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/mnt/work1/software/python/2.7/lib/python2.7/site-packages/optbuild.py&quot;</span>, line <span class=\"m\">57</span>, in _returncode_error_factory\n    raise error_cls, <span class=\"o\">(</span>cmdline, returncode, output, error<span class=\"o\">)</span>\noptbuild.ReturncodeError: /mnt/work1/users/home2/eric.roberts/arch/Linux-x86_64/opt/gmtk-1.4.3/bin/gmtkTriangulate returned <span class=\"m\">1</span>\n</pre></div>\n\n\n<p>Somehow the RuntimeError does not stop Segway from running and Segway attempt to continue to run until gmtkTraingulate fails since the segway.str is filled with 'nan' entries.</p>\n<p>On closer inspection this might be a better error caught in genomedata to avoid issues when something like the \"means\" attribute is used on a genomedata archive. Empty tracks will also raise a RuntimeError (division by zero length).</p>", "type": "rendered"}, "assignee": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "state": "new", "version": null, "edited_on": null, "created_on": "2017-03-24T16:17:25.292230+00:00", "milestone": null, "updated_on": "2017-03-27T18:38:27.176888+00:00", "type": "issue", "id": 106}