{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/119/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/119.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/119/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/119/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/119/semisupervised-mode-fails-when-no-tracks"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/119/vote"}}, "reporter": {"display_name": "Francis Nguyen", "uuid": "{06de6dec-2820-4695-b0e3-b8c48232677f}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B06de6dec-2820-4695-b0e3-b8c48232677f%7D"}, "html": {"href": "https://bitbucket.org/%7B06de6dec-2820-4695-b0e3-b8c48232677f%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:503caffc-22fe-47ba-8947-a81aec8f3bd6/b41d6226-076e-4353-8327-c08d1a612552/128"}}, "nickname": "Francis Nguyen", "type": "user", "account_id": "557058:503caffc-22fe-47ba-8947-a81aec8f3bd6"}, "title": "--semisupervised mode fails when no tracks are specified", "component": null, "votes": 0, "watches": 1, "content": {"raw": "When running `segway train` with `--supervised`, but without specifying `--tracks-from`, Segway v2.0.2 crashes with the following error:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/bin/segway\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py\", line 3743, in main\r\n    return runner()\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py\", line 3508, in __call__\r\n    self.run(*args, **kwargs)\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py\", line 3458, in run\r\n    self.save_gmtk_input()\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py\", line 2053, in save_gmtk_input\r\n    self.save_structure()\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py\", line 1958, in save_structure\r\n    self.clobber)\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/_util.py\", line 156, in __call__\r\n    return save_template(filename, self.resource_name, self.make_mapping(),\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/structure.py\", line 89, in make_mapping\r\n    max_num_datapoints_track = num_datapoints.max()\r\n  File \"/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/numpy/core/_methods.py\", line 26, in _amax\r\n    return umr_maximum(a, axis, None, out, keepdims)\r\nValueError: zero-size array to reduction operation maximum which has no identity\r\n```\r\n\r\nSince `--tracks-from` does not have to be specified when not using `--semisupervised`, this appears to be a bug.\r\n\r\nCurrent workaround is just to remember to specify `--tracks-from` when using `--semisupervised`.", "markup": "markdown", "html": "<p>When running <code>segway train</code> with <code>--supervised</code>, but without specifying <code>--tracks-from</code>, Segway v2.0.2 crashes with the following error:</p>\n<div class=\"codehilite\"><pre><span></span>Traceback (most recent call last):\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/bin/segway&quot;, line 11, in &lt;module&gt;\n    sys.exit(main())\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py&quot;, line 3743, in main\n    return runner()\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py&quot;, line 3508, in __call__\n    self.run(*args, **kwargs)\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py&quot;, line 3458, in run\n    self.save_gmtk_input()\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py&quot;, line 2053, in save_gmtk_input\n    self.save_structure()\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/run.py&quot;, line 1958, in save_structure\n    self.clobber)\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/_util.py&quot;, line 156, in __call__\n    return save_template(filename, self.resource_name, self.make_mapping(),\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/segway/structure.py&quot;, line 89, in make_mapping\n    max_num_datapoints_track = num_datapoints.max()\n  File &quot;/mnt/work1/users/home2/fnguyen/miniconda3/envs/py2.7.3/lib/python2.7/site-packages/numpy/core/_methods.py&quot;, line 26, in _amax\n    return umr_maximum(a, axis, None, out, keepdims)\nValueError: zero-size array to reduction operation maximum which has no identity\n</pre></div>\n\n\n<p>Since <code>--tracks-from</code> does not have to be specified when not using <code>--semisupervised</code>, this appears to be a bug.</p>\n<p>Current workaround is just to remember to specify <code>--tracks-from</code> when using <code>--semisupervised</code>.</p>", "type": "rendered"}, "assignee": null, "state": "new", "version": null, "edited_on": null, "created_on": "2017-12-20T20:21:36.795273+00:00", "milestone": null, "updated_on": "2017-12-20T20:21:36.795273+00:00", "type": "issue", "id": 119}