{"priority": "trivial", "kind": "enhancement", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/122/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/122.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/122/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/122/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/122/save_gmtk_input-hides-exception-raised-by"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/122/vote"}}, "reporter": {"display_name": "Micka\u00ebl Mendez", "uuid": "{3e035b9e-0328-44e8-8622-5c7e9ed060b2}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3e035b9e-0328-44e8-8622-5c7e9ed060b2%7D"}, "html": {"href": "https://bitbucket.org/%7B3e035b9e-0328-44e8-8622-5c7e9ed060b2%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1cb7d89dcab61313d21c5ef402c28e11d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMM-0.png"}}, "nickname": "Mickael Mendez", "type": "user", "account_id": "557058:aae10d90-ba66-49cd-a04d-5392b943760d"}, "title": "save_gmtk_input() hides exception raised by genomedata", "component": null, "votes": 0, "watches": 2, "content": {"raw": "If the code at lines [2028](#!/hoffmanlab/segway/src/e3f58159485fb53103f54fc324192362e1167a49/segway/run.py?at=default&fileviewer=file-view-default#run.py-2028)-[2035](#!/hoffmanlab/segway/src/e3f58159485fb53103f54fc324192362e1167a49/segway/run.py?at=default&fileviewer=file-view-default#run.py-2035) of the run.py file rises an exception, Segway will execute the `finally` clause without reporting the exception.\r\n\r\nFor example, I had to remove the try-finally clause to find out that `Genome() ` raised the following error:\r\n```\r\ntables.exceptions.HDF5ExtError: HDF5 error back trace\r\n\r\n  File \"H5F.c\", line 604, in H5Fopen\r\n    unable to open file\r\n  File \"H5Fint.c\", line 992, in H5F_open\r\n    unable to open file: time = Tue Jan ...\r\n, name = '...chr2.genomedata', tent_flags = 0\r\n  File \"H5FD.c\", line 993, in H5FD_open\r\n    open failed\r\n  File \"H5FDsec2.c\", line 339, in H5FD_sec2_open\r\n    unable to open file: name = '...', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0\r\n\r\nEnd of HDF5 error back trace\r\n```\r\n\r\nFurthermore, if an exception occurs in the list comprehension assigned to `genomes` variable, `genomes` will remain unassigned and the `finally` clause will throw the following exception:\r\n\r\n```\r\nUnboundLocalError: local variable 'genomes' referenced before assignment \r\n```", "markup": "markdown", "html": "<p>If the code at lines <a data-is-external-link=\"true\" href=\"#!/hoffmanlab/segway/src/e3f58159485fb53103f54fc324192362e1167a49/segway/run.py?at=default&amp;fileviewer=file-view-default#run.py-2028\" rel=\"nofollow\">2028</a>-<a data-is-external-link=\"true\" href=\"#!/hoffmanlab/segway/src/e3f58159485fb53103f54fc324192362e1167a49/segway/run.py?at=default&amp;fileviewer=file-view-default#run.py-2035\" rel=\"nofollow\">2035</a> of the run.py file rises an exception, Segway will execute the <code>finally</code> clause without reporting the exception.</p>\n<p>For example, I had to remove the try-finally clause to find out that <code>Genome()</code> raised the following error:</p>\n<div class=\"codehilite\"><pre><span></span>tables.exceptions.HDF5ExtError: HDF5 error back trace\n\n  File &quot;H5F.c&quot;, line 604, in H5Fopen\n    unable to open file\n  File &quot;H5Fint.c&quot;, line 992, in H5F_open\n    unable to open file: time = Tue Jan ...\n, name = &#39;...chr2.genomedata&#39;, tent_flags = 0\n  File &quot;H5FD.c&quot;, line 993, in H5FD_open\n    open failed\n  File &quot;H5FDsec2.c&quot;, line 339, in H5FD_sec2_open\n    unable to open file: name = &#39;...&#39;, errno = 24, error message = &#39;Too many open files&#39;, flags = 0, o_flags = 0\n\nEnd of HDF5 error back trace\n</pre></div>\n\n\n<p>Furthermore, if an exception occurs in the list comprehension assigned to <code>genomes</code> variable, <code>genomes</code> will remain unassigned and the <code>finally</code> clause will throw the following exception:</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"n\">UnboundLocalError</span><span class=\"o\">:</span> <span class=\"n\">local</span> <span class=\"n\">variable</span> <span class=\"s1\">&#39;genomes&#39;</span> <span class=\"n\">referenced</span> <span class=\"n\">before</span> <span class=\"n\">assignment</span> \n</pre></div>", "type": "rendered"}, "assignee": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "state": "new", "version": null, "edited_on": null, "created_on": "2018-01-26T23:00:31.003859+00:00", "milestone": null, "updated_on": "2018-01-29T13:37:57.131586+00:00", "type": "issue", "id": 122}