{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/125/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/125.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/125/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/125/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/125/dry-run-fatal-typeerror"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/125/vote"}}, "reporter": {"display_name": "Francis Nguyen", "uuid": "{06de6dec-2820-4695-b0e3-b8c48232677f}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B06de6dec-2820-4695-b0e3-b8c48232677f%7D"}, "html": {"href": "https://bitbucket.org/%7B06de6dec-2820-4695-b0e3-b8c48232677f%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:503caffc-22fe-47ba-8947-a81aec8f3bd6/b41d6226-076e-4353-8327-c08d1a612552/128"}}, "nickname": "Francis Nguyen", "type": "user", "account_id": "557058:503caffc-22fe-47ba-8947-a81aec8f3bd6"}, "title": "--dry-run fatal TypeError", "component": null, "votes": 0, "watches": 1, "content": {"raw": "While performing a dry run using segway 2.0.2, I ran into this error:\r\n\r\n~~~\r\n/mnt/work1/users/home2/fnguyen/.local/bin/gmtkTriangulate -cppCommandOptions -DCARD_SEG=10 -DCARD_FRAMEINDEX=5000 -DSEGTRANSITION_WEIGHT_SCALE=1.0 -DCARD_SUBSEG=1 -outputTriangulatedFile train_results/triangulation/custom-structure.str.10.1.trifile -strFile custom-structure.str -verbosity 0 \r\n\r\nException in thread Thread-1: \r\n\r\nTraceback (most recent call last): \r\n\r\n  File \"/mnt/work1/users/home2/fnguyen/anaconda3/envs/py27/lib/python2.7/threading.py\", line 801, in __bootstrap_inner \r\n\r\n    self.run() \r\n\r\n  File \"/mnt/work1/users/home2/fnguyen/.local/lib/python2.7/site-packages/segway/run.py\", line 485, in run \r\n\r\n    self.result = self.runner.run_train_instance() \r\n\r\n  File \"/mnt/work1/users/home2/fnguyen/.local/lib/python2.7/site-packages/segway/run.py\", line 2746, in run_train_instance \r\n\r\n    return Results(None, None, None, None, None, None, None) \r\n\r\nTypeError: __new__() takes exactly 9 arguments (8 given) \r\n~~~\r\n\r\nSeems to be missing an extra None.\r\n\r\nThanks.", "markup": "markdown", "html": "<p>While performing a dry run using segway 2.0.2, I ran into this error:</p>\n<div class=\"codehilite\"><pre><span></span>/mnt/work1/users/home2/fnguyen/.local/bin/gmtkTriangulate -cppCommandOptions -DCARD_SEG=10 -DCARD_FRAMEINDEX=5000 -DSEGTRANSITION_WEIGHT_SCALE=1.0 -DCARD_SUBSEG=1 -outputTriangulatedFile train_results/triangulation/custom-structure.str.10.1.trifile -strFile custom-structure.str -verbosity 0 \n\nException in thread Thread-1: \n\nTraceback (most recent call last): \n\n  File &quot;/mnt/work1/users/home2/fnguyen/anaconda3/envs/py27/lib/python2.7/threading.py&quot;, line 801, in __bootstrap_inner \n\n    self.run() \n\n  File &quot;/mnt/work1/users/home2/fnguyen/.local/lib/python2.7/site-packages/segway/run.py&quot;, line 485, in run \n\n    self.result = self.runner.run_train_instance() \n\n  File &quot;/mnt/work1/users/home2/fnguyen/.local/lib/python2.7/site-packages/segway/run.py&quot;, line 2746, in run_train_instance \n\n    return Results(None, None, None, None, None, None, None) \n\nTypeError: __new__() takes exactly 9 arguments (8 given) \n</pre></div>\n\n\n<p>Seems to be missing an extra None.</p>\n<p>Thanks.</p>", "type": "rendered"}, "assignee": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-03-16T19:11:35.195189+00:00", "milestone": null, "updated_on": "2018-08-24T14:57:31.020962+00:00", "type": "issue", "id": 125}