{"priority": "trivial", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/8/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/8.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/8/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/8/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/8/segway-should-not-requeue-jobs-that-failed"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/8/vote"}}, "reporter": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "title": "Segway should not requeue jobs that failed for reasons other than out-of-memory", "component": null, "votes": 0, "watches": 1, "content": {"raw": "From Google Code Issue #13\n\n**Imported Labels**: bug, imported, Priority-Low\n\n_From [jay.hesselberth](https://code.google.com/u/jay.hesselberth/) on August 18, 2010 12:29:09_\n\nI migrated some segway training runs from one file system to another; this changed the root path and so the .inc files referenced by segway.inc and input.master changed.  When I initiate an identify run, the gmtkTriangulate task raises and exception and exits the segway run cleanly:\r\n\r\n/segway-projects/results/20100812/exp1/segway.str:1:70: error: /segway-results/results/20100812/exp1/auxiliary/segway.inc: No such file or directory\r\nParse Error in file '/segway-projects/results/20100812/exp1/segway.str': expecting variable type at or before line 7, near (TYPE_SEGCOUNTDOWN)\r\nExiting Program\r\nTraceback (most recent call last):\r\n  File \"/segway-build/arch/Linux-x86_64/bin/segway\", line 8, in <module>\r\n    load_entry_point('segway==0.2.0', 'console_scripts', 'segway')()\r\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/run.py\", line 3694, in main\r\n    return runner()\r\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/run.py\", line 3514, in __call__\r\n    self.run(*args, **kwargs)\r\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/run.py\", line 3487, in run\r\n    self.run_triangulate()\r\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/run.py\", line 3084, in run_triangulate\r\n    self.run_triangulate_single(num_segs)\r\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/run.py\", line 3077, in run_triangulate_single\r\n    prog(**kwargs)\r\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 78, in __call__\r\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 209, in run\r\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 191, in _getoutput\r\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 154, in _popen\r\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 54, in _returncode_error_factory\r\noptbuild.ReturncodeError: /segway-build/arch/Linux-x86_64/bin/gmtkTriangulate returned 1\r\n\r\nHowever, the gmtkViterbi task that uses input.master recognizes the error and raises and exception, but then (apparently) thinks it exited because it ran out of memory and launches another job with increased memory requirements (below; there are multiple of these errors in a row as it keeps trying to launch the same job repeatedly).  Rather than doing this, it should exit cleanly as above because the model isn't correctly parsed.\r\n\r\nroot@ip-10-204-151-58\r\n/segway-projects/results/20100818/exp1/20100818.identify.20100818/output/e/identify\r\n> cat vit999.20100818.identify.20100818.196ffc5aaadf11dfbaf712313b0a94cc\r\n/segway-build/arch/Linux-x86_64/lib/python2.6/path-2.2-py2.6.egg/path.py:32:\r\nDeprecationWarning: the md5 module is deprecated; use hashlib instead\r\n/segway-build/arch/Linux-x86_64/lib/python2.6/optbuild-0.1.7-py2.6.egg/optbuild.py:294:\r\nDeprecationWarning: object.__new__() takes no parameters\r\n/segway-build/arch/Linux-x86_64/lib/python2.6/tables/leaf.py:415:\r\nPerformanceWarning: The Leaf ``/supercontig_5/continuous`` is\r\nexceeding the maximum recommended rowsize (32000000 bytes);\r\nbe ready to see PyTables asking for *lots* of memory and possibly slow\r\nI/O.  You may want to reduce the rowsize by trimming the value of\r\ndimensions that are orthogonal (and preferably close) to the main\r\ndimension of this leave.  Alternatively, in case you have specified a\r\nvery small/large chunksize, you may want to increase/decrease it.\r\n PerformanceWarning)\r\n/segway-projects/results/20100812/exp1/params/input.master:1:70:\r\nerror: /segway-results/results/20100812/exp1/auxiliary/segway.inc: No\r\nsuch file or directory\r\nERROR: In file '/segway-projects/results/20100812/exp1/params/input.master'\r\nline 18, DT 'map_frameIndex_ruler', equation 'mod(p0, RULER_SCALE) ==\r\n0 ':  Invalid symbol at 'ruler_scale)==0'\r\nTraceback (most recent call last):\r\n File \"/segway-build/arch/Linux-x86_64/bin/segway-task\", line 8, in <module>\r\n   load_entry_point('segway==0.2.0', 'console_scripts', 'segway-task')()\r\n File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/task.py\",\r\nline 242, in main\r\n   return task(*args)\r\n File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/task.py\",\r\nline 234, in task\r\n   TASKS[verb, kind]((chrom, start, end), resolution, outfilename, *args)\r\n File \"/segway-build/arch/Linux-x86_64/lib/python2.6/segway-0.2.0-py2.6.egg/segway/task.py\",\r\nline 211, in run_viterbi_save_bed\r\n   output = VITERBI_PROG.getoutput(*args)\r\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 203, in getoutput\r\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 191, in _getoutput\r\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 154, in _popen\r\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 54, in\r\n_returncode_error_factory\r\noptbuild.ReturncodeError:\r\n/segway-build/arch/Linux-x86_64/bin/gmtkViterbi returned 1\n\n_Original issue: http://code.google.com/p/segway-genome/issues/detail?id=13_", "markup": "markdown", "html": "<p>From Google Code Issue <a href=\"#!/hoffmanlab/segway/issues/13/supervision-labels-are-disabled-during\" rel=\"nofollow\" title=\"Supervision labels are disabled during identify\" class=\"ap-connect-link\">#13</a></p>\n<p><strong>Imported Labels</strong>: bug, imported, Priority-Low</p>\n<p><em>From <a data-is-external-link=\"true\" href=\"https://code.google.com/u/jay.hesselberth/\" rel=\"nofollow\">jay.hesselberth</a> on August 18, 2010 12:29:09</em></p>\n<p>I migrated some segway training runs from one file system to another; this changed the root path and so the .inc files referenced by segway.inc and input.master changed.  When I initiate an identify run, the gmtkTriangulate task raises and exception and exits the segway run cleanly:</p>\n<p>/segway-projects/results/20100812/exp1/segway.str:1:70: error: /segway-results/results/20100812/exp1/auxiliary/segway.inc: No such file or directory\nParse Error in file '/segway-projects/results/20100812/exp1/segway.str': expecting variable type at or before line 7, near (TYPE_SEGCOUNTDOWN)\nExiting Program\nTraceback (most recent call last):\n  File \"/segway-build/arch/Linux-x86_64/bin/segway\", line 8, in &lt;module&gt;\n    load_entry_point('segway==0.2.0', 'console_scripts', 'segway')()\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/run.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/run.py</a>\", line 3694, in main\n    return runner()\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/run.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/run.py</a>\", line 3514, in <strong>call</strong>\n    self.run(*args, <strong>kwargs)\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/run.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/run.py</a>\", line 3487, in run\n    self.run_triangulate()\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/run.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/run.py</a>\", line 3084, in run_triangulate\n    self.run_triangulate_single(num_segs)\n  File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/run.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/run.py</a>\", line 3077, in run_triangulate_single\n    prog(</strong>kwargs)\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 78, in <strong>call</strong>\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 209, in run\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 191, in _getoutput\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 154, in _popen\n  File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 54, in _returncode_error_factory\noptbuild.ReturncodeError: /segway-build/arch/Linux-x86_64/bin/gmtkTriangulate returned 1</p>\n<p>However, the gmtkViterbi task that uses input.master recognizes the error and raises and exception, but then (apparently) thinks it exited because it ran out of memory and launches another job with increased memory requirements (below; there are multiple of these errors in a row as it keeps trying to launch the same job repeatedly).  Rather than doing this, it should exit cleanly as above because the model isn't correctly parsed.</p>\n<p>root@ip-10-204-151-58\n/segway-projects/results/20100818/exp1/20100818.identify.20100818/output/e/identify</p>\n<blockquote>\n<p>cat vit999.<a href=\"#!/hoffmanlab/segway/commits/20100818\" rel=\"nofollow\" class=\"ap-connect-link\">20100818</a>.identify.<a href=\"#!/hoffmanlab/segway/commits/20100818\" rel=\"nofollow\" class=\"ap-connect-link\">20100818</a>.<a href=\"#!/hoffmanlab/segway/commits/196ffc5aaadf11dfbaf712313b0a94cc\" rel=\"nofollow\" class=\"ap-connect-link\">196ffc5aaadf11dfbaf712313b0a94cc</a>\n/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://path-2.2-py2.6.egg/path.py:32\" rel=\"nofollow\" class=\"ap-connect-link\">path-2.2-py2.6.egg/path.py:32</a>:\nDeprecationWarning: the md5 module is deprecated; use hashlib instead\n/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://optbuild-0.1.7-py2.6.egg/optbuild.py:294\" rel=\"nofollow\" class=\"ap-connect-link\">optbuild-0.1.7-py2.6.egg/optbuild.py:294</a>:\nDeprecationWarning: object.<strong>new</strong>() takes no parameters\n/segway-build/arch/Linux-x86_64/lib/python2.6/tables/leaf.py:415:\nPerformanceWarning: The Leaf <code>/supercontig_5/continuous</code> is\nexceeding the maximum recommended rowsize (<a href=\"#!/hoffmanlab/segway/commits/32000000\" rel=\"nofollow\" class=\"ap-connect-link\">32000000</a> bytes);\nbe ready to see PyTables asking for <em>lots</em> of memory and possibly slow\nI/O.  You may want to reduce the rowsize by trimming the value of\ndimensions that are orthogonal (and preferably close) to the main\ndimension of this leave.  Alternatively, in case you have specified a\nvery small/large chunksize, you may want to increase/decrease it.\n PerformanceWarning)\n/segway-projects/results/20100812/exp1/params/input.master:1:70:\nerror: /segway-results/results/20100812/exp1/auxiliary/segway.inc: No\nsuch file or directory\nERROR: In file '/segway-projects/results/20100812/exp1/params/input.master'\nline 18, DT 'map_frameIndex_ruler', equation 'mod(p0, RULER_SCALE) ==\n0 ':  Invalid symbol at 'ruler_scale)==0'\nTraceback (most recent call last):\n File \"/segway-build/arch/Linux-x86_64/bin/segway-task\", line 8, in &lt;module&gt;\n   load_entry_point('segway==0.2.0', 'console_scripts', 'segway-task')()\n File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/task.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/task.py</a>\",\nline 242, in main\n   return task(<em>args)\n File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/task.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/task.py</a>\",\nline 234, in task\n   TASKS<a data-is-external-link=\"true\" href=\"/hoffmanlab/segway/src/f04cce0da8be2a440391951445c15aa6e3f37f77/(chrom,%20start,%20end),%20resolution,%20outfilename,%20*args\" rel=\"nofollow\">verb, kind</a>\n File \"/segway-build/arch/Linux-x86_64/lib/python2.6/<a href=\"http://segway-0.2.0-py2.6.egg/segway/task.py\" rel=\"nofollow\" class=\"ap-connect-link\">segway-0.2.0-py2.6.egg/segway/task.py</a>\",\nline 211, in run_viterbi_save_bed\n   output = VITERBI_PROG.getoutput(</em>args)\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 203, in getoutput\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 191, in _getoutput\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 154, in _popen\n File \"build/bdist.linux-x86_64/egg/optbuild.py\", line 54, in\n_returncode_error_factory\noptbuild.ReturncodeError:\n/segway-build/arch/Linux-x86_64/bin/gmtkViterbi returned 1</p>\n</blockquote>\n<p><em>Original issue: <a href=\"http://code.google.com/p/segway-genome/issues/detail?id=13\" rel=\"nofollow\" class=\"ap-connect-link\">http://code.google.com/p/segway-genome/issues/detail?id=13</a></em></p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2014-06-09T18:34:19.401788+00:00", "milestone": null, "updated_on": "2016-02-23T19:42:22.088355+00:00", "type": "issue", "id": 8}