{"priority": "blocker", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/segway/issues/95/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/issues/95.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/95/watch"}, "comments": {"href": "data/repositories/hoffmanlab/segway/issues/95/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/segway/issues/95/runtime-error-error-126-in-output-files"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/issues/95/vote"}}, "reporter": null, "title": "Runtime error. Error 126 in output files. Permission denied over sh executable files", "component": null, "votes": 0, "watches": null, "content": {"raw": "segway --num-labels=4 train test.genomedata traindir\r\n traindir/observations/chr21.0000.float32 (9411193, 9595548)\r\n____ PROGRAM ENDED SUCCESSFULLY WITH STATUS 0 AT Tuesday November 22 2016, 15:36:50 CET ____\r\nrunning locally 1: emt0.0.0.traindir.1ac69340b0c111e6a5ac989096c35828 ()\r\nrunning locally 2: emt0.0.0.traindir.1ac69340b0c111e6a5ac989096c35828 ()\r\nTraceback (most recent call last):\r\n  File \"/usr/local/bin/segway\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 3030, in main\r\n    return runner()\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2823, in __call__\r\n    self.run(*args, **kwargs)\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2790, in run\r\n    self.run_train()\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2334, in run_train\r\n    instance_params = run_train_func(self.num_segs_range)\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2343, in run_train_singlethread\r\n    res = [self.run_train_instance()]\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2222, in run_train_instance\r\n    round_index, kwargs)\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2229, in progress_train_instance\r\n    self.run_train_round(self.instance_index, round_index, **kwargs)\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2173, in run_train_round\r\n    restartable_jobs.wait()\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/cluster/__init__.py\", line 306, in wait\r\n    self.process_job(jobid, job_info)\r\n  File \"/usr/local/lib/python2.7/dist-packages/segway/cluster/__init__.py\", line 258, in process_job\r\n    (jobid, job_name, error_filename))\r\nRuntimeError: \r\nSubmitted Job (2) failed. Failed Job: emt0.0.0.traindir.1ac69340b0c111e6a5ac989096c35828.\r\nFor details, check error messages in traindir/output/e/0/emt0.0.0.traindir.1ac69340b0c111e6a5ac989096c35828.\r\nSee the Troubleshooting section of the Segway documentation.", "markup": "markdown", "html": "<p>segway --num-labels=4 train test.genomedata traindir\n traindir/observations/chr21.0000.float32 (<a href=\"#!/hoffmanlab/segway/commits/9411193\" rel=\"nofollow\" class=\"ap-connect-link\">9411193</a>, <a href=\"#!/hoffmanlab/segway/commits/9595548\" rel=\"nofollow\" class=\"ap-connect-link\">9595548</a>)\n<strong><em>_ PROGRAM ENDED SUCCESSFULLY WITH STATUS 0 AT Tuesday November 22 2016, 15:36:50 CET </em></strong>_\nrunning locally 1: emt0.0.0.traindir.<a href=\"#!/hoffmanlab/segway/commits/1ac69340b0c111e6a5ac989096c35828\" rel=\"nofollow\" class=\"ap-connect-link\">1ac69340b0c111e6a5ac989096c35828</a> ()\nrunning locally 2: emt0.0.0.traindir.<a href=\"#!/hoffmanlab/segway/commits/1ac69340b0c111e6a5ac989096c35828\" rel=\"nofollow\" class=\"ap-connect-link\">1ac69340b0c111e6a5ac989096c35828</a> ()\nTraceback (most recent call last):\n  File \"/usr/local/bin/segway\", line 11, in &lt;module&gt;\n    sys.exit(main())\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 3030, in main\n    return runner()\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2823, in <strong>call</strong>\n    self.run(*args, <strong>kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2790, in run\n    self.run_train()\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2334, in run_train\n    instance_params = run_train_func(self.num_segs_range)\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2343, in run_train_singlethread\n    res = [self.run_train_instance()]\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2222, in run_train_instance\n    round_index, kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2229, in progress_train_instance\n    self.run_train_round(self.instance_index, round_index, </strong>kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/segway/run.py\", line 2173, in run_train_round\n    restartable_jobs.wait()\n  File \"/usr/local/lib/python2.7/dist-packages/segway/cluster/<strong>init</strong>.py\", line 306, in wait\n    self.process_job(jobid, job_info)\n  File \"/usr/local/lib/python2.7/dist-packages/segway/cluster/<strong>init</strong>.py\", line 258, in process_job\n    (jobid, job_name, error_filename))\nRuntimeError: \nSubmitted Job (2) failed. Failed Job: emt0.0.0.traindir.<a href=\"#!/hoffmanlab/segway/commits/1ac69340b0c111e6a5ac989096c35828\" rel=\"nofollow\" class=\"ap-connect-link\">1ac69340b0c111e6a5ac989096c35828</a>.\nFor details, check error messages in traindir/output/e/0/emt0.0.0.traindir.<a href=\"#!/hoffmanlab/segway/commits/1ac69340b0c111e6a5ac989096c35828\" rel=\"nofollow\" class=\"ap-connect-link\">1ac69340b0c111e6a5ac989096c35828</a>.\nSee the Troubleshooting section of the Segway documentation.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2016-11-22T14:44:46.256825+00:00", "milestone": null, "updated_on": "2016-11-25T14:28:06.386445+00:00", "type": "issue", "id": 95}