{"rendered": {"reason": {"raw": "These changesets were concatenated and resubmitted in pull request #23", "markup": "markdown", "html": "<p>These changesets were concatenated and resubmitted in <a href=\"#!/hoffmanlab/segway/pull-requests/23/fix-simplerecover-test-when-reading\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #23</a></p>", "type": "rendered"}, "description": {"raw": "This is a follow up to Issue 32 and Pull Request 20. \r\n\r\nPart of the fix to Issue 32 in Pull Request 20 cause the following autobuild failure in test case simplerecover\r\n\r\n```\r\n#!\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/virtualenv/python2.7/bin/segway\", line 9, in <module>\r\n    load_entry_point('segway==1.2.2.dev0', 'console_scripts', 'segway')()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2583, in main\r\n    return runner()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2395, in __call__\r\n    self.run(*args, **kwargs)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2361, in run\r\n    self.run_train()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1948, in run_train\r\n    instance_params = run_train_func(self.num_segs_range)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1957, in run_train_singlethread\r\n    res = [self.run_train_instance()]\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1819, in run_train_instance\r\n    self.make_instance_initial_results()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2129, in make_instance_initial_results\r\n    log_likelihood)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2087, in recover_train_instance\r\n    with open(recover_log_likelihood_tab_filepath) \\\r\nIOError: [Errno 2] No such file or directory: path('../recover/traindir/log/likelihood.0.tab')\r\n```\r\n\r\nThe cause of this error is because we decide to let likelihood tab file have the same name as the likelihood file. In this case, its trying to recover a single-instance run, where the likelihood file has been renamed to likelihood.ll so the tab file name lis likelihood.tab.\r\n\r\nThe fix might seems \u201cbad\u201d, but that\u2019s the only good one I could think of for now.\r\n\r\nThe root cause of this problem and the Issue 32 is the fundamental difference how segway treat single instance and multiple instances. Despite the fact that the main run function of the two are the same, in multi instance case it use the result of set_log_likelihood_filenames call in the main run function, while in single instance, this function is called but ignored. They also have a different way wrap up after the main part of training has finished, where likelihood file is not wrapped up at the end of the single instance case. The best way to fix this is to refactoring the whole part which would be extremely costly and I would not recommend that.", "markup": "markdown", "html": "<p>This is a follow up to Issue 32 and Pull Request 20. </p>\n<p>Part of the fix to Issue 32 in Pull Request 20 cause the following autobuild failure in test case simplerecover</p>\n<div class=\"codehilite\"><pre><span></span>Traceback (most recent call last):\n  File &quot;/home/ubuntu/virtualenv/python2.7/bin/segway&quot;, line 9, in &lt;module&gt;\n    load_entry_point(&#39;segway==1.2.2.dev0&#39;, &#39;console_scripts&#39;, &#39;segway&#39;)()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2583, in main\n    return runner()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2395, in __call__\n    self.run(*args, **kwargs)\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2361, in run\n    self.run_train()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 1948, in run_train\n    instance_params = run_train_func(self.num_segs_range)\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 1957, in run_train_singlethread\n    res = [self.run_train_instance()]\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 1819, in run_train_instance\n    self.make_instance_initial_results()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2129, in make_instance_initial_results\n    log_likelihood)\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2087, in recover_train_instance\n    with open(recover_log_likelihood_tab_filepath) \\\nIOError: [Errno 2] No such file or directory: path(&#39;../recover/traindir/log/likelihood.0.tab&#39;)\n</pre></div>\n\n\n<p>The cause of this error is because we decide to let likelihood tab file have the same name as the likelihood file. In this case, its trying to recover a single-instance run, where the likelihood file has been renamed to likelihood.ll so the tab file name lis likelihood.tab.</p>\n<p>The fix might seems \u201cbad\u201d, but that\u2019s the only good one I could think of for now.</p>\n<p>The root cause of this problem and the Issue 32 is the fundamental difference how segway treat single instance and multiple instances. Despite the fact that the main run function of the two are the same, in multi instance case it use the result of set_log_likelihood_filenames call in the main run function, while in single instance, this function is called but ignored. They also have a different way wrap up after the main part of training has finished, where likelihood file is not wrapped up at the end of the single instance case. The best way to fix this is to refactoring the whole part which would be extremely costly and I would not recommend that.</p>", "type": "rendered"}, "title": {"raw": "Fix the autobuild won't pass caused by could not find tab file by adding a test to see if the file exists.", "markup": "markdown", "html": "<p>Fix the autobuild won't pass caused by could not find tab file by adding a test to see if the file exists.</p>", "type": "rendered"}}, "type": "pullrequest", "description": "This is a follow up to Issue 32 and Pull Request 20. \r\n\r\nPart of the fix to Issue 32 in Pull Request 20 cause the following autobuild failure in test case simplerecover\r\n\r\n```\r\n#!\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/virtualenv/python2.7/bin/segway\", line 9, in <module>\r\n    load_entry_point('segway==1.2.2.dev0', 'console_scripts', 'segway')()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2583, in main\r\n    return runner()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2395, in __call__\r\n    self.run(*args, **kwargs)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2361, in run\r\n    self.run_train()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1948, in run_train\r\n    instance_params = run_train_func(self.num_segs_range)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1957, in run_train_singlethread\r\n    res = [self.run_train_instance()]\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1819, in run_train_instance\r\n    self.make_instance_initial_results()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2129, in make_instance_initial_results\r\n    log_likelihood)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2087, in recover_train_instance\r\n    with open(recover_log_likelihood_tab_filepath) \\\r\nIOError: [Errno 2] No such file or directory: path('../recover/traindir/log/likelihood.0.tab')\r\n```\r\n\r\nThe cause of this error is because we decide to let likelihood tab file have the same name as the likelihood file. In this case, its trying to recover a single-instance run, where the likelihood file has been renamed to likelihood.ll so the tab file name lis likelihood.tab.\r\n\r\nThe fix might seems \u201cbad\u201d, but that\u2019s the only good one I could think of for now.\r\n\r\nThe root cause of this problem and the Issue 32 is the fundamental difference how segway treat single instance and multiple instances. Despite the fact that the main run function of the two are the same, in multi instance case it use the result of set_log_likelihood_filenames call in the main run function, while in single instance, this function is called but ignored. They also have a different way wrap up after the main part of training has finished, where likelihood file is not wrapped up at the end of the single instance case. The best way to fix this is to refactoring the whole part which would be extremely costly and I would not recommend that.", "links": {"decline": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/pullrequests/22/decline"}, "diffstat": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/diffstat/Tamaki_Sakura/segway:acfdabab54d5%0D003236384a66?from_pullrequest_id=22"}, "commits": {"href": "data/repositories/hoffmanlab/segway/pullrequests/22/commits.json"}, "self": {"href": "data/repositories/hoffmanlab/segway/pullrequests/22.json"}, "comments": {"href": "data/repositories/hoffmanlab/segway/pullrequests/22/comments_page=1.json"}, "merge": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/pullrequests/22/merge"}, "html": {"href": "#!/hoffmanlab/segway/pull-requests/22"}, "activity": {"href": "data/repositories/hoffmanlab/segway/pullrequests/22/activity.json"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/diff/Tamaki_Sakura/segway:acfdabab54d5%0D003236384a66?from_pullrequest_id=22"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/segway/pullrequests/22/approve"}, "statuses": {"href": "data/repositories/hoffmanlab/segway/pullrequests/22/statuses_page=1.json"}}, "title": "Fix the autobuild won't pass caused by could not find tab file by adding a test to see if the file exists.", "close_source_branch": false, "reviewers": [{"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}], "id": 22, "destination": {"commit": {"hash": "003236384a66", "type": "commit", "links": {"self": {"href": "data/repositories/hoffmanlab/segway/commit/003236384a66.json"}, "html": {"href": "#!/hoffmanlab/segway/commits/003236384a66"}}}, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/segway.json"}, "html": {"href": "#!/hoffmanlab/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}ts=python"}}, "type": "repository", "name": "segway", "full_name": "hoffmanlab/segway", "uuid": "{68bf38bf-f0c1-4c9c-909e-0ee4b2c26257}"}, "branch": {"name": "default"}}, "created_on": "2015-06-12T20:33:08.282486+00:00", "summary": {"raw": "This is a follow up to Issue 32 and Pull Request 20. \r\n\r\nPart of the fix to Issue 32 in Pull Request 20 cause the following autobuild failure in test case simplerecover\r\n\r\n```\r\n#!\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/virtualenv/python2.7/bin/segway\", line 9, in <module>\r\n    load_entry_point('segway==1.2.2.dev0', 'console_scripts', 'segway')()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2583, in main\r\n    return runner()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2395, in __call__\r\n    self.run(*args, **kwargs)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2361, in run\r\n    self.run_train()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1948, in run_train\r\n    instance_params = run_train_func(self.num_segs_range)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1957, in run_train_singlethread\r\n    res = [self.run_train_instance()]\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 1819, in run_train_instance\r\n    self.make_instance_initial_results()\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2129, in make_instance_initial_results\r\n    log_likelihood)\r\n  File \"/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py\", line 2087, in recover_train_instance\r\n    with open(recover_log_likelihood_tab_filepath) \\\r\nIOError: [Errno 2] No such file or directory: path('../recover/traindir/log/likelihood.0.tab')\r\n```\r\n\r\nThe cause of this error is because we decide to let likelihood tab file have the same name as the likelihood file. In this case, its trying to recover a single-instance run, where the likelihood file has been renamed to likelihood.ll so the tab file name lis likelihood.tab.\r\n\r\nThe fix might seems \u201cbad\u201d, but that\u2019s the only good one I could think of for now.\r\n\r\nThe root cause of this problem and the Issue 32 is the fundamental difference how segway treat single instance and multiple instances. Despite the fact that the main run function of the two are the same, in multi instance case it use the result of set_log_likelihood_filenames call in the main run function, while in single instance, this function is called but ignored. They also have a different way wrap up after the main part of training has finished, where likelihood file is not wrapped up at the end of the single instance case. The best way to fix this is to refactoring the whole part which would be extremely costly and I would not recommend that.", "markup": "markdown", "html": "<p>This is a follow up to Issue 32 and Pull Request 20. </p>\n<p>Part of the fix to Issue 32 in Pull Request 20 cause the following autobuild failure in test case simplerecover</p>\n<div class=\"codehilite\"><pre><span></span>Traceback (most recent call last):\n  File &quot;/home/ubuntu/virtualenv/python2.7/bin/segway&quot;, line 9, in &lt;module&gt;\n    load_entry_point(&#39;segway==1.2.2.dev0&#39;, &#39;console_scripts&#39;, &#39;segway&#39;)()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2583, in main\n    return runner()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2395, in __call__\n    self.run(*args, **kwargs)\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2361, in run\n    self.run_train()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 1948, in run_train\n    instance_params = run_train_func(self.num_segs_range)\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 1957, in run_train_singlethread\n    res = [self.run_train_instance()]\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 1819, in run_train_instance\n    self.make_instance_initial_results()\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2129, in make_instance_initial_results\n    log_likelihood)\n  File &quot;/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/segway-1.2.2.dev0-py2.7.egg/segway/run.py&quot;, line 2087, in recover_train_instance\n    with open(recover_log_likelihood_tab_filepath) \\\nIOError: [Errno 2] No such file or directory: path(&#39;../recover/traindir/log/likelihood.0.tab&#39;)\n</pre></div>\n\n\n<p>The cause of this error is because we decide to let likelihood tab file have the same name as the likelihood file. In this case, its trying to recover a single-instance run, where the likelihood file has been renamed to likelihood.ll so the tab file name lis likelihood.tab.</p>\n<p>The fix might seems \u201cbad\u201d, but that\u2019s the only good one I could think of for now.</p>\n<p>The root cause of this problem and the Issue 32 is the fundamental difference how segway treat single instance and multiple instances. Despite the fact that the main run function of the two are the same, in multi instance case it use the result of set_log_likelihood_filenames call in the main run function, while in single instance, this function is called but ignored. They also have a different way wrap up after the main part of training has finished, where likelihood file is not wrapped up at the end of the single instance case. The best way to fix this is to refactoring the whole part which would be extremely costly and I would not recommend that.</p>", "type": "rendered"}, "source": {"commit": {"hash": "acfdabab54d5", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/Tamaki_Sakura/segway/commit/acfdabab54d5"}, "html": {"href": "https://bitbucket.org/Tamaki_Sakura/segway/commits/acfdabab54d5"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/Tamaki_Sakura/segway"}, "html": {"href": "https://bitbucket.org/Tamaki_Sakura/segway"}, "avatar": {"href": "data/bytebucket.org/ravatar/{99c18329-33d0-4f18-af6e-158fbae1f679}ts=python"}}, "type": "repository", "name": "segway", "full_name": "Tamaki_Sakura/segway", "uuid": "{99c18329-33d0-4f18-af6e-158fbae1f679}"}, "branch": {"name": "change_ll_name"}}, "comment_count": 20, "state": "DECLINED", "task_count": 0, "participants": [{"role": "REVIEWER", "participated_on": "2015-06-16T14:15:52.754801+00:00", "type": "participant", "approved": false, "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}}, {"role": "PARTICIPANT", "participated_on": "2015-06-16T14:37:33.037093+00:00", "type": "participant", "approved": false, "user": {"display_name": "Sakura Tamaki", "uuid": "{2e49c073-0cbe-4333-96b1-a81988007690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2e49c073-0cbe-4333-96b1-a81988007690%7D"}, "html": {"href": "https://bitbucket.org/%7B2e49c073-0cbe-4333-96b1-a81988007690%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:8f562ae3-ccee-4990-9d3f-58dc4e5d4282/860719ec-a458-4597-a2c0-04bb410a3373/128"}}, "nickname": "Tamaki_Sakura", "type": "user", "account_id": "557058:8f562ae3-ccee-4990-9d3f-58dc4e5d4282"}}, {"role": "PARTICIPANT", "participated_on": "2015-06-15T15:59:52.176958+00:00", "type": "participant", "approved": false, "user": {"display_name": "Michael Hoffman", "uuid": "{ffa8e039-5d4d-4f69-a4ba-ac25cbaf700b}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bffa8e039-5d4d-4f69-a4ba-ac25cbaf700b%7D"}, "html": {"href": "https://bitbucket.org/%7Bffa8e039-5d4d-4f69-a4ba-ac25cbaf700b%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/6a95e857a02504cbad5fe965c9d9e4bbd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMH-1.png"}}, "nickname": "hoffman", "type": "user", "account_id": "557058:a9657985-692c-405c-995b-4e41cda7ba2b"}}], "reason": "These changesets were concatenated and resubmitted in pull request #23", "updated_on": "2015-06-16T18:18:07.225403+00:00", "author": {"display_name": "Sakura Tamaki", "uuid": "{2e49c073-0cbe-4333-96b1-a81988007690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2e49c073-0cbe-4333-96b1-a81988007690%7D"}, "html": {"href": "https://bitbucket.org/%7B2e49c073-0cbe-4333-96b1-a81988007690%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:8f562ae3-ccee-4990-9d3f-58dc4e5d4282/860719ec-a458-4597-a2c0-04bb410a3373/128"}}, "nickname": "Tamaki_Sakura", "type": "user", "account_id": "557058:8f562ae3-ccee-4990-9d3f-58dc4e5d4282"}, "merge_commit": null, "closed_by": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}}